spring.datasource.url=jdbc:postgresql://db.zyoqrbcdjkymdctkhhnc.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Lyne002Assouh

spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}spring.datasource.url=jdbc:postgresql://db.zyoqrbcdjkymdctkhhnc.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=ASSOUH2002ELISME

spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}